version: '3.8'

services:

  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main_container
    depends_on:
      - helper
    volumes:
      - ${PWD}:/usr/src/app

  helper:
    image: ubuntu:22.04
    container_name: helper_container
    environment:
      - HELPER_VAR=123
    command: sleep 10000
